import type {Answer,QuestionSet} from '../core/types';
import {grade} from '../core/engine';
export type ActivityKind='understanding'|'poll'|'quick'|'assessment'|'raid'|'external';
export interface Participant{id:string;nickname:string;joinedAt:number;help:boolean}
export interface Submission{id:string;participantId:string;activityId:string;questionId:string;answer:Answer;correct:boolean;at:number;durationMs:number}
export interface Activity{id:string;kind:ActivityKind;title:string;instructions:string;startedAt:number;endsAt:number;endedAt?:number;set?:QuestionSet;questionIndex:number;options:string[];url?:string;hp:number;maxHp:number;contributions:string[]}
export interface Room{code:string;title:string;owner:string;createdAt:number;expiresAt:number;closedAt?:number;version:number;participants:Participant[];activities:Activity[];current?:Activity;submissions:Submission[];questions:{id:string;text:string;resolved:boolean}[]}
const key=(code:string)=>'wq.demo.room.'+code;
export function makeRoom(title:string,owner:string,code:string,now=Date.now()):Room{return{code,title:title.trim().slice(0,80)||'오늘의 수업',owner,createdAt:now,expiresAt:now+86400000,version:1,participants:[],activities:[],submissions:[],questions:[]};}
export function readRoom(code:string):Room|null{const raw=localStorage.getItem(key(code));if(!raw)return null;try{const r=JSON.parse(raw) as Room;if(Date.now()>r.expiresAt+86400000||r.closedAt&&Date.now()>r.closedAt+86400000){localStorage.removeItem(key(code));return null;}return r;}catch{return null;}}
function persist(r:Room){if(r.current){const index=r.activities.findIndex(a=>a.id===r.current?.id);if(index>=0)r.activities[index]=r.current;}r.version++;localStorage.setItem(key(r.code),JSON.stringify(r));}
export async function createRoom(title:string):Promise<Room>{let code='';for(let n=0;n<20;n++){code=String(100000+crypto.getRandomValues(new Uint32Array(1))[0]%900000);if(!readRoom(code))break;code='';}if(!code)throw Error('수업 코드를 만들지 못했습니다. 다시 시도하세요.');const owner=crypto.randomUUID();const r=makeRoom(title,owner,code);persist(r);sessionStorage.setItem('wq.demo.teacher',JSON.stringify({code,owner}));return r;}
async function change(code:string,fn:(r:Room)=>void){const run=()=>{const r=readRoom(code);if(!r)throw Error('수업방을 찾을 수 없습니다.');fn(r);persist(r);return r;};return navigator.locks?navigator.locks.request(key(code),run):run();}
function alive(r:Room){if(r.closedAt||r.expiresAt<=Date.now())throw Error('종료되거나 만료된 수업입니다.');}
function teacher(r:Room,owner:string){if(r.owner!==owner)throw Error('교사 제어 정보가 일치하지 않습니다.');}
export async function joinRoom(code:string,nickname:string){if(!/^\d{6}$/.test(code))throw Error('6자리 코드를 입력하세요.');if(!nickname.trim()||nickname.trim().length>20)throw Error('번호 또는 별명을 1~20자로 입력하세요.');const id=sessionStorage.getItem('wq.demo.student.'+code)||crypto.randomUUID();const r=await change(code,room=>{alive(room);if(!room.participants.some(p=>p.id===id)){if(room.participants.length>=50)throw Error('최대 50명까지 참여할 수 있습니다.');room.participants.push({id,nickname:nickname.trim(),joinedAt:Date.now(),help:false});}});sessionStorage.setItem('wq.demo.student.'+code,id);return{room:r,participantId:id};}
export async function addDemoStudents(code:string,owner:string){return change(code,r=>{teacher(r,owner);alive(r);for(let i=1;i<=3;i++)if(!r.participants.some(p=>p.id==='demo-'+i))r.participants.push({id:'demo-'+i,nickname:'체험 학생 '+i,joinedAt:Date.now(),help:false});});}
export async function startActivity(code:string,owner:string,options:{kind:ActivityKind;title:string;instructions:string;minutes:number;set?:QuestionSet;options?:string[];url?:string}){return change(code,r=>{teacher(r,owner);alive(r);if(r.current&&!r.current.endedAt)throw Error('현재 활동을 종료한 뒤 다음 활동을 시작하세요.');const maxHp=Math.max(1,Math.ceil(r.participants.length*(options.set?.questions.length||1)*.7));const activity:Activity={id:crypto.randomUUID(),kind:options.kind,title:options.title.slice(0,80),instructions:options.instructions.slice(0,2000),startedAt:Date.now(),endsAt:Date.now()+Math.min(options.kind==='raid'?5:60,Math.max(1,options.minutes))*60000,set:options.set,questionIndex:0,options:options.options||[],url:options.url,hp:maxHp,maxHp,contributions:[]};r.current=activity;r.activities.push(activity);});}
export async function endActivity(code:string,owner:string){return change(code,r=>{teacher(r,owner);if(r.current)r.current.endedAt=Date.now();});}
export async function nextQuestion(code:string,owner:string){return change(code,r=>{teacher(r,owner);alive(r);if(!r.current?.set||r.current.endedAt)throw Error('진행 중인 문제 활동이 없습니다.');r.current.questionIndex=Math.min(r.current.questionIndex+1,r.current.set.questions.length-1);});}
export async function extendActivity(code:string,owner:string,deltaSeconds:number){return change(code,r=>{teacher(r,owner);alive(r);if(!r.current||r.current.endedAt)throw Error('진행 중인 활동이 없습니다.');const cap=r.current.kind==='raid'?r.current.startedAt+300000:r.current.startedAt+3600000;r.current.endsAt=Math.min(cap,Math.max(Date.now()+1000,r.current.endsAt+deltaSeconds*1000));});}
export async function closeRoom(code:string,owner:string){return change(code,r=>{teacher(r,owner);r.closedAt=Date.now();if(r.current)r.current.endedAt=Date.now();});}
export function applyAnswer(r:Room,input:{id:string;participantId:string;activityId:string;questionId:string;answer:Answer;durationMs:number},now=Date.now()):Submission{alive(r);if(!r.participants.some(p=>p.id===input.participantId))throw Error('참여자가 아닙니다.');const a=r.current;if(!a||a.id!==input.activityId||a.endedAt||a.endsAt<=now)throw Error('활동이 끝났습니다. 현재 활동을 확인하세요.');const duplicate=r.submissions.find(s=>s.id===input.id);if(duplicate){if(duplicate.participantId!==input.participantId)throw Error('제출 ID가 충돌했습니다.');return duplicate;}
let correct=false;if(a.kind==='understanding'||a.kind==='poll'){if(typeof input.answer!=='number'||!Number.isInteger(input.answer)||input.answer<0||input.answer>=a.options.length)throw Error('올바른 선택지를 고르세요.');if(r.submissions.some(s=>s.activityId===a.id&&s.participantId===input.participantId))throw Error('이미 응답했습니다.');}else if(a.kind==='external'){throw Error('외부 활동은 교사 확인으로 완료합니다.');}else{const q=a.set?.questions.find(q=>q.id===input.questionId);if(!q)throw Error('현재 문제를 찾을 수 없습니다.');if(a.kind!=='raid'&&a.set?.questions[a.questionIndex].id!==q.id)throw Error('이전 문제의 제출입니다.');if(a.kind!=='raid'&&r.submissions.some(s=>s.activityId===a.id&&s.participantId===input.participantId&&s.questionId===q.id))throw Error('이미 제출한 문제입니다.');correct=grade(q,input.answer);const contribution=input.participantId+':'+q.id;if(a.kind==='raid'&&correct&&!a.contributions.includes(contribution)){a.contributions.push(contribution);a.hp=Math.max(0,a.hp-1);}}
const s:Submission={...input,correct,at:now,durationMs:Math.max(0,Math.min(3600000,input.durationMs))};r.submissions.push(s);return s;}
export async function submitAnswer(code:string,input:Parameters<typeof applyAnswer>[1]){let result:Submission|undefined;await change(code,r=>{result=applyAnswer(r,input);});return result!;}
export async function requestHelp(code:string,id:string){return change(code,r=>{alive(r);const p=r.participants.find(p=>p.id===id);if(!p)throw Error('참여자를 확인하세요.');p.help=!p.help;});}
export async function askQuestion(code:string,id:string,text:string){if(!text.trim()||text.length>500)throw Error('질문은 1~500자로 작성하세요.');return change(code,r=>{alive(r);if(!r.participants.some(p=>p.id===id))throw Error('참여자가 아닙니다.');r.questions.push({id:crypto.randomUUID(),text:text.trim(),resolved:false});});}
export async function resolveQuestion(code:string,owner:string,id:string){return change(code,r=>{teacher(r,owner);const q=r.questions.find(q=>q.id===id);if(q)q.resolved=!q.resolved;});}
export function firstAttempts(r:Room,activityId?:string){const seen=new Set<string>();return r.submissions.filter(s=>{if(activityId&&s.activityId!==activityId)return false;const k=s.activityId+':'+s.participantId+':'+s.questionId;if(seen.has(k))return false;seen.add(k);return true;});}
