import type {QuestionSet} from '../core/types';
import {firstAttempts,type Room} from '../classroom/demo-room';
import {teamboardCards} from '../core/exports';
export interface HandoffItem{id:string;kind:'announcement'|'wrong-cards'|'groups'|'questions';target:'class'|'teamboard';title:string;body:string;createdAt:number;expiresAt:number;roomCode:string}
export function loadHandoffs():HandoffItem[]{try{const items=JSON.parse(localStorage.getItem('wq.handoffs')||'[]') as HandoffItem[];const valid=items.filter(x=>x.expiresAt>Date.now());if(valid.length!==items.length)localStorage.setItem('wq.handoffs',JSON.stringify(valid));return valid;}catch{return[];}}
export function saveHandoff(item:HandoffItem){localStorage.setItem('wq.handoffs',JSON.stringify([...loadHandoffs().filter(x=>x.id!==item.id),item]));}
export function saveRaidHandoff(room:Room){const a=room.current;if(!a?.set||!a.endedAt||a.kind!=='raid')return;saveHandoff({id:room.code+':'+a.id,kind:'wrong-cards',target:'teamboard',title:'레이드 오답 성찰',body:teamboardCards(a.set,firstAttempts(room,a.id).map(s=>({questionId:s.questionId,answer:s.answer,correct:s.correct}))),createdAt:Date.now(),expiresAt:room.expiresAt,roomCode:room.code});}
export function reviewSet(room:Room):QuestionSet|null{const a=[...room.activities].reverse().find(a=>a.set);if(!a?.set)return null;const count=new Map<string,number>();for(const s of firstAttempts(room,a.id))if(!s.correct)count.set(s.questionId,(count.get(s.questionId)||0)+1);const questions=a.set.questions.filter(q=>count.has(q.id)).sort((a,b)=>(count.get(b.id)||0)-(count.get(a.id)||0));if(!questions.length)return null;return{...a.set,id:a.set.id+'-review-'+room.code,title:room.title+' · 오답 복습',questions};}
export async function cardImage(title:string,body:string):Promise<Blob>{const lines=body.split('\n').flatMap(line=>line.match(/.{1,38}/gu)||['']);const canvas=document.createElement('canvas');canvas.width=900;canvas.height=160+lines.length*32;const c=canvas.getContext('2d');if(!c)throw Error('이미지 생성 불가');c.fillStyle='#eef8f5';c.fillRect(0,0,canvas.width,canvas.height);c.fillStyle='#143e50';c.font='bold 30px sans-serif';c.fillText(title,40,60);c.font='22px sans-serif';lines.forEach((line,i)=>c.fillText(line,40,115+i*32));return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('이미지 생성 실패')),'image/png'));}
