import {describe,it,expect,vi,afterEach} from 'vitest';
import {detectMode,chooseMode} from '../packages/context/modes';
import {makeRoom,applyAnswer,firstAttempts,type Room} from '../packages/classroom/demo-room';
import {saveRaidHandoff,loadHandoffs,reviewSet} from '../packages/handoff/store';
import type {QuestionSet} from '../packages/core/types';
const set:QuestionSet={schemaVersion:'1.0',id:'set',version:1,title:'연습',questions:[{id:'q',type:'multiple-choice',prompt:'2+2',options:['3','4'],answer:1,tags:['수학'],standard:'교사 확인 목표'}]};
function room():Room{const r=makeRoom('수업','owner','123456');r.participants=[{id:'private-id',nickname:'개인별명',joinedAt:Date.now(),help:false}];r.current={id:'a',kind:'raid',title:'raid',instructions:'',startedAt:Date.now(),endsAt:Date.now()+300000,set,questionIndex:0,options:[],hp:5,maxHp:5,contributions:[]};r.activities=[r.current];return r;}
const input=(id='s',answer=1)=>({id,participantId:'private-id',activityId:'a',questionId:'q',answer,durationMs:500});
afterEach(()=>vi.unstubAllGlobals());
describe('context URL-only rules',()=>{it('class/teamboard/remote exact hosts and generic fallback',()=>{expect(detectMode('https://class.whalespace.io/my')).toBe('class');expect(detectMode('https://teamboard.whalespace.io/board')).toBe('teamboard');expect(detectMode('https://study.whaleon.naver.com/room')).toBe('remote');expect(detectMode('https://other.example/pdf')).toBe('lesson');});it('rejects host suffix tricks, nonhttps and malformed URLs',()=>{expect(detectMode('https://class.whalespace.io.evil.test/')).toBe('lesson');expect(detectMode('http://class.whalespace.io/')).toBe('lesson');expect(detectMode('not-url')).toBe('lesson');});it('manual override can never bypass UBT pause',()=>{expect(chooseMode('https://ubt.whalespace.io/exam','lesson')).toBe('paused');expect(chooseMode('https://class.whalespace.io','teamboard')).toBe('teamboard');});});
describe('demo grading/raid integrity',()=>{it('ignores client point claims and grades actual answer',()=>{const r=room();expect(applyAnswer(r,input('wrong',0)).correct).toBe(false);expect(r.current?.hp).toBe(5);expect(applyAnswer(r,input('right',1)).correct).toBe(true);expect(r.current?.hp).toBe(4);});it('deduplicates same submission and repeated correct contributions',()=>{const r=room();applyAnswer(r,input());applyAnswer(r,input());applyAnswer(r,input('retry'));expect(r.submissions).toHaveLength(2);expect(r.current?.hp).toBe(4);});it('rejects nonparticipants/old activities/expired/closed submissions',()=>{const r=room();expect(()=>applyAnswer(r,{...input(),participantId:'other'})).toThrow();expect(()=>applyAnswer(r,{...input(),activityId:'old'})).toThrow();r.current!.endsAt=Date.now()-1;expect(()=>applyAnswer(r,input())).toThrow();r.closedAt=Date.now();expect(()=>applyAnswer(r,input())).toThrow();});it('first attempts denominator ignores retry duplicates',()=>{const r=room();applyAnswer(r,input('wrong',0));applyAnswer(r,input('correct',1));expect(firstAttempts(r)).toHaveLength(1);expect(reviewSet(r)?.questions).toHaveLength(1);});it('exports aggregates without participant names/IDs and prunes expired handoffs',()=>{const values=new Map<string,string>();vi.stubGlobal('localStorage',{getItem:(k:string)=>values.get(k)||null,setItem:(k:string,v:string)=>values.set(k,v)});const r=room();applyAnswer(r,input('wrong',0));r.current!.endedAt=Date.now();saveRaidHandoff(r);const text=loadHandoffs()[0].body;expect(text).toContain('2+2');expect(text).not.toContain('개인별명');expect(text).not.toContain('private-id');r.expiresAt=Date.now()-1;saveRaidHandoff(r);expect(loadHandoffs()).toHaveLength(0);});});
