import {useEffect,useRef,useState} from 'react';
import {modeNames,type SidebarMode} from '../context/modes';
import {useTabContext} from '../context/use-context';
import {appFrameOrigin,appFrameSrc} from '../shared/extension';
const modeIcons={class:'🐢',teamboard:'🐙',remote:'🦑',lesson:'🐳'};
export function ContextSidebar({url}:{url:string}){const context=useTabContext();const [overrides,setOverrides]=useState<Record<string,SidebarMode>>({});const frame=useRef<HTMLIFrameElement>(null);const tab=String(context.tabId||'web-preview');const mode=context.mode==='paused'?'paused':overrides[tab]||context.mode;
function notify(){if(url&&frame.current?.contentWindow)frame.current.contentWindow.postMessage({type:'WQ_MODE',mode},appFrameOrigin(url));}
useEffect(()=>{notify();});
return <section className={'context-sidebar mode-'+mode} aria-label="상황 인식 사이드바"><div className="sidebar-modes" role="group" aria-label="사이드바 모드">{(['class','teamboard','remote','lesson'] as const).map(m=>{return <button disabled={context.mode==='paused'} aria-pressed={m===mode} key={m} onClick={()=>setOverrides({...overrides,[tab]:m})}><span className="mode-emoji" aria-hidden="true">{modeIcons[m]}</span>{modeNames[m]}</button>;})}</div><p className="sidebar-mode-line" role="status"><span>{context.mode==='paused'?'UBT 평가 감지':overrides[tab]?'직접 선택한 모드':'현재 탭에 맞춰 자동 전환'} · {modeNames[mode]}</span>{overrides[tab]&&context.mode!=='paused'&&<button onClick={()=>setOverrides(previous=>{const next={...previous};delete next[tab];return next;})}>자동으로</button>}</p>{mode==='paused'&&<p role="alert" className="pause-banner">평가 중에는 학생 대상 기능을 사용할 수 없습니다. UBT 탭을 벗어나세요.</p>}{url?<iframe ref={frame} title="수업 운영과 전달물" src={appFrameSrc(url)} onLoad={notify} className="sidebar-workbench" style={{visibility:mode==='paused'?'hidden':'visible'}}/>:<p>설정에서 웹앱 주소를 저장해 주세요.</p>}</section>;}
