import {useEffect,useState} from 'react';
import {ArrowUpRight,Link2,CheckCircle2,Settings2,PanelRightOpen,Users,BookOpen,ChevronRight} from 'lucide-react';
import {isExtension,loadAppUrl,openApp,saveAppUrl} from '../shared/extension';
import {ContextSidebar} from './ContextSidebar';
import {Brand,WhaleArt} from './Brand';
export function Sidebar(){
 const [url,setUrl]=useState('');const [draft,setDraft]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [ready,setReady]=useState(false);const [error,setError]=useState(false);
 useEffect(()=>{let active=true;loadAppUrl().then(value=>{if(active){setUrl(value);setDraft(value);}}).catch(e=>{if(active){setError(true);setMessage(e instanceof Error?e.message:'주소를 불러오지 못했습니다.');}}).finally(()=>{if(active)setReady(true);});return()=>{active=false;};},[]);
 async function act(fn:()=>Promise<void>){if(busy)return;setBusy(true);setMessage('');setError(false);try{await fn();}catch(e){setError(true);setMessage(e instanceof Error?e.message:'다시 시도해 주세요.');}finally{setBusy(false);}}
 return <div className="sidebar-shell"><a className="skip-link" href="#sidebar-main">본문으로 건너뛰기</a><header><Brand/><span className="mini-phase">수업 순환</span></header><main id="sidebar-main"><div className="sidebar-status"><CheckCircle2 size={15}/>{isExtension()?'웨일 확장앱에서 실행 중':'웹 미리보기 · 설치 검증과 별도'}</div><section className="sidebar-hero"><span className="eyebrow">YOUR CLASSROOM, CONNECTED</span><h1>수업 곁에,<br/>작은 배움의 바다.</h1><p>지금 보고 있는 수업 화면을 유지하고<br/>웹앱으로 자연스럽게 이어가세요.</p><WhaleArt/></section><section className="connection-panel"><div className="small-heading"><Link2 size={19}/><h2>웹앱 연결</h2></div><p>{url?'연결한 웹앱을 새 탭에서 엽니다.':'웹앱 주소를 저장하면 새 탭으로 바로 열 수 있어요.'}</p>{url&&<span className="saved-url" title={url}>{url}</span>}<button className="primary full" disabled={!ready||!url||busy} onClick={()=>void act(()=>openApp(url))}>웹앱 열기<ArrowUpRight size={18}/></button><details open={!url}><summary><Settings2 size={15}/>연결 설정</summary><form onSubmit={e=>{e.preventDefault();void act(async()=>{const value=await saveAppUrl(draft);setUrl(value);setDraft(value);setMessage('웹앱 주소를 저장했습니다.');});}}><label htmlFor="web-url">웹앱 기본 주소</label><input id="web-url" type="text" inputMode="url" autoComplete="url" spellCheck={false} value={draft} placeholder="https://your-app.vercel.app" maxLength={2048} onChange={e=>setDraft(e.target.value)} disabled={busy||!ready}/><p className="input-help">배포한 HTTPS 주소를 입력하세요. 로컬 개발 주소도 사용할 수 있습니다.</p><button type="submit" disabled={busy||!ready}>{busy?'저장 중…':'주소 저장'}</button></form></details>{message&&<p className={error?'notice error':'notice success'} role={error?'alert':'status'}>{message}</p>}</section><ContextSidebar url={url}/><section className="up-next"><div className="small-heading"><h2>수업 순환 안내</h2><span>시연 모드</span></div>{[[PanelRightOpen,'수업 도구','랜덤 뽑기 · 모둠 · 타이머 · QR'],[Users,'함께하는 수업','이해도 체크 · 형성평가 · 협동 레이드'],[BookOpen,'혼자 이어가는 학습','집중 학습 · 오답 복습 · 완료 카드']].map(([Icon,title,description])=>{const I=Icon as typeof Users;return <div className="next-row" key={String(title)}><I size={20}/><div><strong>{String(title)}</strong><p>{String(description)}</p></div><ChevronRight size={15}/></div>;})}</section><p className="sidebar-footnote">시연 모드는 동일 브라우저만 연결합니다. 실제 다중 기기 수업에는 Supabase 설정과 검증이 필요합니다.</p></main><footer>WHALE QUEST <span>수업을 연결하는 작은 도구</span></footer></div>;
}
